### ISSUE TITLE
[Enhancement] Sellers peds with ox_target

### ISSUE THREAD

**Issue by Oldarorn** [wasabirobby/wasabi_oxshops#6]
Hello,

I'm actually trying your ressource and I like it ! Pretty good to use and clear but I wanted to suggest you to add a npc handling, it would be more natural than a simple "press E" notification and we could be able to choose if we want to press a control or use ox_target to open the shop !

Thank for your great work !

**Comment by wasabirobby** [comment]
I will add very soon :)

**Comment by TheSilentGhost** [comment]
> I will add very soon :)

Any update on this?
