### ISSUE TITLE
Improper createItem hook usage

### ISSUE THREAD

**Issue by thelindat** [wasabirobby/wasabi_oxshops#9]
https://github.com/overextended/ox_inventory/issues/1243
https://github.com/overextended/ox_inventory/issues/1244

This code assumes an item is successfully added to the player, however createItem is more like "creatingItem" and is triggered before checking for slots, stacking, etc. Should also  be using the inventory filter.
https://github.com/wasabirobby/wasabi_oxshops/blob/c3fddb03f97bfd148b8e812131e003753e4e990d/server/server.lua#L50-L60

Use [buyItem hook](https://github.com/overextended/ox_inventory/blob/0901a5e881f7803beed5befe930c79f4d52a7439/modules/shops/server.lua#L245-L257) instead.

While I'm here, it shouldn't be necessary to remove hooks on resource stop (handled internally).

https://github.com/wasabirobby/wasabi_oxshops/blob/c3fddb03f97bfd148b8e812131e003753e4e990d/server/server.lua#L97-L105

https://github.com/overextended/ox_inventory/blob/main/modules/hooks/server.lua#L111-L123

**Comment by lirola** [comment]
can this be solved?
[script:wasabi_oxshop] SCRIPT ERROR: @wasabi_oxshops/server/server.lua:29: attempt to index a nil value (field 'shopData')
[script:wasabi_oxshop] > <unknown> (@oxmysql/dist/build.js:22033)
[script:wasabi_oxshop] > processTicksAndRejections (node:internal/process/task_queues:96)

**Comment by lirola** [comment]
> To solve my error, atleast, i needed to edit the ox_inventory and adding the ESX funcitons. The problem was on the calls of cannot_carry or unable_stack_items the script of wasabi's will always add the money indeed i removed the createItem options or editing it on this way (buyItem).
> 
> So idk why he do that, but with that workaround i did.. all working good.

can you show me fix?

**Comment by ynnniV** [comment]
It's simply - Just do removemoney when showing the erros.

**Comment by lirola** [comment]
> It's simply - Just do removemoney when showing the erros.

					stashItems[#stashItems + 1] = { name = v.name, metadata = v.metadata, count = v.count, price = (v.metadata.shopData.price or 0) }
what do i have remove?

**Comment by ynnniV** [comment]
> > It's simply - Just do removemoney when showing the erros.
> 
> ```
> 				stashItems[#stashItems + 1] = { name = v.name, metadata = v.metadata, count = v.count, price = (v.metadata.shopData.price or 0) }
> ```
> 
> what do i have remove?

You no need to remove nothing. Just add ESX to do something on ox_inventory.
Then u need to do the workaroud. Where the error are cannot_carry and unable_stack_items you need to call the society and remove the price.

**Comment by wasabirobby** [comment]
Thanks @thelindat , I have made the appropriate changes.
